name: nucleo
description: 'A Flutter package for real-time communication and event handling through Firebase Cloud Messaging, WebSockets, and HTTP Polling, with background task support'
version: 0.0.1
homepage:

environment:
  sdk: ^3.5.4
  flutter: '>=1.17.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_messaging: ^15.1.5
  web_socket_channel: ^3.0.1
  http: ^1.2.2
  background_fetch: ^1.3.7
  firebase_core: ^3.8.0
  flutter_secure_storage: ^9.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
